"""add is_free to lessons

Revision ID: 0d602edf2396
Revises: a4f090975991
Create Date: 2026-03-31 19:28:19.293779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d602edf2396'
down_revision: Union[str, None] = 'a4f090975991'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('is_free', sa.Boolean(), nullable=True))

    op.execute("UPDATE lessons SET is_free = false")

    op.alter_column('lessons', 'is_free', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'is_free')
    # ### end Alembic commands ###
