"""remove is_free from courses

Revision ID: 348065596db6
Revises: 0d602edf2396
Create Date: 2026-04-04 22:37:04.329310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '348065596db6'
down_revision: Union[str, None] = '0d602edf2396'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'is_free')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('is_free', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
